name: Publish

on:
    push:
        tags:
            - "**[0-9]+.[0-9]+.[0-9]+*"

permissions:
    contents: write
    packages: write
    actions: write

jobs:
    docker:
        name: Build / Push Docker Images
        runs-on: ubuntu-latest
        env:
            BUILDX_BAKE_ENTITLEMENTS_FS: 0
        steps:
            - uses: actions/checkout@v6

            - name: Calculate Version and Pre-release State
              id: meta
              run: |
                  REF="${GITHUB_REF_NAME}"
                  CLEAN_VERSION="${REF#v}"

                  echo "VERSION=$CLEAN_VERSION" >> $GITHUB_ENV

                  # Bash check: Does the version contain a hyphen?
                  if [[ "$CLEAN_VERSION" == *"-"* ]]; then
                     echo "IS_PRERELEASE=true" >> $GITHUB_ENV
                     echo "prerelease"
                  else
                     echo "IS_PRERELEASE=false" >> $GITHUB_ENV
                  fi

            - name: Setup Registries
              run: |
                  OWNER="${GITHUB_REPOSITORY_OWNER,,}"
                  echo "REGISTRIES=ghcr.io/${OWNER}" >> $GITHUB_ENV
                  echo "CACHE_REPO=ghcr.io/${OWNER}/locket" >> $GITHUB_ENV

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4
              with:
                  driver: docker-container

            - name: Login to GHCR
              uses: docker/login-action@v4
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build / Push
              working-directory: docker
              env:
                  REGISTRIES: ${{ env.REGISTRIES }}
                  PLATFORMS: linux/amd64
                  CI: false
              run: |
                  docker buildx bake \
                      --allow=fs.read=.. \
                      -f docker-bake.hcl \
                      bao \
                      --push \
                      --metadata-file metadata.json
